site_name: "ASA: Serviços para 2º bimestre"
site_author: Dario da silva 

theme:
  name: readthedocs

![Logo do GitHub](https://github.com/Dariosilv/asa-2023-2-2bim/blob/main/public/images/logo.png?raw=true&hash=<hash-da-imagem>)
